id: P29532F23
initial_creation_type: ocr
source_metadata:
  volumes:
    b3b3a31a650c46af8446d299693376a8:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: རབ་ཏུ་གནས་པའི་རྒྱན།
      total_pages: 1853
      volume_number: 25
