id: P29532F23
initial_creation_type: ocr
source_metadata:
  volumes:
    d28951a3dc6648248b1150231f930e96:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: རབ་ཏུ་གནས་པའི་རྒྱན།
      total_pages: 1853
      volume_number: 25
